// Code generated by 'go generate'; DO NOT EDIT.

package wslapi

import (
	"syscall"
	"unsafe"

	"golang.org/x/sys/windows"
)

var _ unsafe.Pointer

// Do the interface allocations only once for common
// Errno values.
const (
	errnoERROR_IO_PENDING = 997
)

var (
	errERROR_IO_PENDING error = syscall.Errno(errnoERROR_IO_PENDING)
	errERROR_EINVAL     error = syscall.EINVAL
)

// errnoErr returns common boxed Errno values, to prevent
// allocations at runtime.
func errnoErr(e syscall.Errno) error {
	switch e {
	case 0:
		return errERROR_EINVAL
	case errnoERROR_IO_PENDING:
		return errERROR_IO_PENDING
	}
	// TODO: add more here, after collecting data on the common
	// error values see on Windows. (perhaps when running
	// all.bat?)
	return e
}

var (
	modwslapi = windows.NewLazySystemDLL("wslapi.dll")

	procWslIsDistributionRegistered = modwslapi.NewProc("WslIsDistributionRegistered")
	procWslRegisterDistribution     = modwslapi.NewProc("WslRegisterDistribution")
)

func _WslIsDistributionRegistered(distributionName *uint16) (res bool) {
	r0, _, _ := syscall.Syscall(procWslIsDistributionRegistered.Addr(), 1, uintptr(unsafe.Pointer(distributionName)), 0, 0)
	res = r0 != 0
	return
}

func _WslRegisterDistribution(distributionName *uint16, tarGzFilename *uint16) (res error) {
	r0, _, _ := syscall.Syscall(procWslRegisterDistribution.Addr(), 2, uintptr(unsafe.Pointer(distributionName)), uintptr(unsafe.Pointer(tarGzFilename)), 0)
	if r0 != 0 {
		res = syscall.Errno(r0)
	}
	return
}
